"""add_tax_profiles_table

Revision ID: 5f406792e1d9
Revises: 143d055b23e5
Create Date: 2026-07-17 23:24:09.480660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f406792e1d9'
down_revision: Union[str, Sequence[str], None] = '143d055b23e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('salary_income', sa.Boolean(), nullable=False),
    sa.Column('business_income', sa.Boolean(), nullable=False),
    sa.Column('house_property', sa.Boolean(), nullable=False),
    sa.Column('capital_gain', sa.Boolean(), nullable=False),
    sa.Column('other_sources', sa.Boolean(), nullable=False),
    sa.Column('foreign_assets', sa.Boolean(), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('financial_year', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_tax_profiles_id'), 'tax_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_profiles_id'), table_name='tax_profiles')
    op.drop_table('tax_profiles')
    # ### end Alembic commands ###
